baseURL = 'https://ddchristiantan.github.io/mtportfolio'
languageCode = 'en-us'
title = 'Martin Tan'
paginate = 5
theme = 'papermod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "MartinTan"
description = "def"
keywords = [ "Data Analyst", "Portfolio", "Data Science" ]
author = "Martin Tan"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.label]
  text = "Martin Tan"

  [params.profileMode]
  enabled = true
  title = "Welcome! 👋"
  subtitle = " abc-def"
  imageUrl = "/images/dp.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "dp"

    [[params.profileMode.buttons]]
    name = "Blogs"
    url = "blogs"

    [[params.profileMode.buttons]]
    name = "Projects"
    url = "projects"

  [params.homeInfoParams]
  Title = "Welcome! 👋"
  Content = "xyz"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/chanin-nantasenamat/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/dataprofessor"

  [[params.socialIcons]]
  name = "buymeacoffee"
  url = "https://www.buymeacoffee.com/dataprofessor"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = false

  [params.editPost]
  URL = ""
  Text = ""
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
identifier = "blog"
name = "Blogs"
url = "/blogs/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 2
